# 站点名称
site_name: 榆树 的 Wiki

# 站点描述
site_description: 这是一个基于 MkDocs 构建的 Wiki 站点

# 站点作者
site_author: yuwb

# 站点 URL（如果要部署的话）
site_url: https://yuwb-dy.github.io/yuwb-wiki/

# 文档目录
docs_dir: docs

# 输出目录
# site_dir: site

# 主题
theme:
  name: material
  font:
    text: 
      zh: "Noto Serif SC, 思源宋体, serif"
      en: "Roboto, Arial, sans-serif"
    code: "Fira Code, Consolas, monospace"
  features:
    - navigation.tabs
    - navigation.indexes
    - navigation.sections
    - toc.integrate
    - navigation.top
  palette:
    primary: blue
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
extra_css:
  - stylesheets/custom.css
# 导航结构
nav:
  - 首页: index.md
  - 指南: guides.md
  - API文档: api.md
  - 关于: about.md

#  markdown 扩展
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:pymdownx.emoji.twemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# 如果需要明确指定插件，只保留默认的 search 插件
plugins:
  - search
# 版权信息
copyright: Copyright &copy; 2025 yuwb
